# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MSQ Timetable' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MSQ Timetable

pod 'Alamofire'
pod 'RxSwift', '~> 5'
pod 'RxCocoa', '~> 5'
pod 'Kingfisher'


end
